#!/bin/bash

foreground="#D5C4A1"
mainForeground="#FBF1C7"
    # -P "Open:" \
    # -p "Open app:" \

bemenu \
    -l 10 \
    -C \
    -I \
    -e \
    -B 3 \
    -R 5 \
    -n \
    -w \
    -W 0.9 \
    -m HDMI-A-1 \
    --binding vim \
    --scrollbar none \
    --fn "JetbrainsMono Nerd Font 12" \
    --tf "$mainForeground" \
    --tb "#689D6A"  \
    --ff "$mainForeground" \
    --fb "#8EC07C" \
    --cb "#928374" \
    --cf "#928374" \
    --nb "#1D2021" \
    --nf "$foreground" \
    --hb "#D65D0E" \
    --hf "$mainForeground" \
    --fbb "#CC241D" \
    --fbf "#CC241D" \
    --sb  "#CC241D" \
    --sf  "#CC241D" \
    --ab "#3C3836" \
    --af "$foreground" \
    "$@"
